.TH SPEAKUPCONF "1" "March 2009" "Speakup Tools" "User Commands"
.SH NAME
speakupconf \- script to load/save all the vars in speakup
.SH SYNOPSIS
\fBspeakupconf\fR save|load
.SH DESCRIPTION
.B Speakupconf
is a script that saves and restores speakup's customizable variables.

If it is run as root, it saves in /etc/speakup, or, if it is run as a
user, it saves in $HOME/.speakup.  This means that each user can have
unique speakup settings.
.SH AUTHOR
Steve Holmes

This manual page was written by Samuel Thibault <samuel.thibault@ens-lyon.org>,
It is distributed under the GPLv2 or any other version.
