.TH SPEAKUPCONF "1" "March 2009" "Speakup conf" "User Commands"
.SH NAME
speakupconf \- script to load/save all the vars in speakup
.SH SYNOPSIS
\fBspeakupconf\fR save|load
.SH DESCRIPTION
.B Speakupconf
is a script that saves and restores speakup's customizable variables.
.SH AUTHOR
Steve Holmes

This manual page was written by Samuel Thibault <samuel.thibault@ens-lyon.org>,
It is distributed under the GPLv2 or any other version.
