.TH SPEAKWITH "1" "March 2009" "Speak with" "User Commands"
.SH NAME
talkwith \- script to easily switch speakup speech synthesizer
.SH SYNOPSIS
\fBtalkwith\fR \fIsynth\fR [ -x ]
.SH DESCRIPTION
.B talkwith
permits to easily make speakup switch between various speech synthesizers,
including the espeak software synthesizer (through espeakup).
.SH AUTHOR
Charles Hallenbeck, chuckh@.ftml.net

This manual page was written by Samuel Thibault <samuel.thibault@ens-lyon.org>,
It is distributed under the GPLv2 or any other version.
