#!/bin/sh
#
# talkwith -- switches speakup synthesizers on the fly
#
# Bug reports, suggestions, etc. to chuckh@ftml.net
#
# This script requires Linux kernel 2.6.24 or higher
# Talkwith requires espeak and espeakup for software speech
# and speakupconf to load and save speakup settings
# To install talkwith, simply copy this script to /usr/local/sbin
# On my system, the /etc/rc.local file contains a statement like this:
#
# start talking
#export PATH=/usr/local/bin:/usr/local/sbin:$PATH
#talkwith soft
#
if [ ! -d /sys/module/speakup ]
then
        echo ${0}: The kernel does not contain speakup. 1>&2
        exit 1
fi
#
if [ "$1" = "" ] || [ "$2" != "" ] || \
[ "$1" = "-h" ] || [ "$1" = "--help" ]; then
echo "Usage: `basename $0` <synth>"
echo
echo "You may use one of the following synthesizer names if the driver"
echo "has been selected and the corresponding device is available:"
echo "acntsa, acntpc, apollo, audptr, bns, dectlk, decext, decpc, dtlk,"
echo "keypc, ltlk, soft, spkout, txprt, dummy, or none."
echo "Use speakupconf to save speech settings to load at startup"
exit
fi
#
if [ "$1" != "none" ] && \
# To disallow a particular device, comment out its line below:
[ "$1" != "acntsa" ] && \
[ "$1" != "acntpc" ] && \
[ "$1" != "apollo" ] && \
[ "$1" != "audptr" ] && \
[ "$1" != "bns" ] && \
[ "$1" != "dectlk" ] && \
[ "$1" != "decext" ] && \
[ "$1" != "decpc" ] && \
[ "$1" != "dtlk" ] && \
[ "$1" != "keypc" ] && \
[ "$1" != "ltlk" ] && \
[ "$1" != "spkout" ] && \
[ "$1" != "txprt" ] && \
[ "$1" != "dummy" ] && \
# do not comment out the next line!
[ "$1" != "soft" ]; then
echo "Unrecognized synthesizer type: \"$1\""
exit 1
fi
#
F1="`cat /sys/module/speakup/parameters/synth`"
if [ "$F1" != "none" ]; then
echo "none" > /sys/module/speakup/parameters/synth
if [ "$F1" = "soft" ]; then
kill `cat /var/run/speechd-up.pid` >/dev/null 2>&1
kill `cat /var/run/espeakup.pid` >/dev/null 2>&1
fi
sleep 1
fi
#
if [ "$1" = "none" ]; then
exit
fi
#
echo "$1" >/sys/module/speakup/parameters/synth
if [ "$1" = "soft" ]; then
espeakup >/dev/null 2>&1
fi
speakupconf load
