#!/bin/bash
# Applies speakup to kernel sources
# Usage: ./install-speakup <KERNELDIR>

die() {
	echo $*
	exit 1
}

KDIR=${1:-/usr/src/linux}
SPKDIR=$(pwd)

[[ -d ${KDIR} ]] || die "${KDIR} is not a directory"
[[ -e ${KDIR}/MAINTAINERS ]] || die "${KDIR} is not a kernel dir"
[[ -e ${KDIR}/drivers/char/speakup/spkglue.c ]] ||
	die "spkglue must be installed to ${KDIR} first"

cat ${SPKDIR}/src/Kbuild >> ${KDIR}/drivers/char/speakup/Makefile
cp ${SPKDIR}/src/*.[ch] ${SPKDIR}/src/Kconfig ${KDIR}/drivers/char/speakup

echo "speakup installed to ${KDIR}"
