#!/bin/bash
# Installs speakup to kernel sources
# Usage: ./install <KERNELDIR> [copy]

die() {
	echo $*
	exit 1
}

KDIR=${1:-/usr/src/linux}
SPKDIR=$(pwd)

[[ -d ${KDIR} ]] || die "${KDIR} is not a directory"
[[ -e ${KDIR}/MAINTAINERS ]] || die "${KDIR} is not a kernel dir"

patch -d ${KDIR} -l -p1 -N -i ${SPKDIR}/spkglue/kernel-integration.patch ||
	die "spkglue/kernel-integration.patch patching failed"

if ["$2"] != "copy"]; then
	ln -s ${SPKDIR}/src ${KDIR}/drivers/char/speakup
	ln -s ${SPKDIR}/doc ${KDIR}/Documentation/speakup
	echo "speakup has been installed to ${KDIR}"
else
	cp -R ${SPKDIR}/src ${KDIR}/drivers/char/speakup
	cp -R ${SPKDIR}/doc ${KDIR}/Documentation/speakup
	echo "speakup has been installed and copied to ${KDIR}"
fi
