#!/bin/bash
# Makes a tarball release

SPKVER=$(./version)
PREFIX=speakup-${SPKVER}
REL=${1:-v${SPKVER}}

if [ "$REL" != "v${SPKVER}" ]; then
	TIMESTAMP=$(git show $REL --pretty=format:%ai | head -1)
	PATCHLEVEL=$(date --utc -d "$TIMESTAMP" +_p%Y%m%d%H%M)
fi

TARFILE=${PREFIX}${PATCHLEVEL}.tar

git archive --prefix=${PREFIX}/ $REL -o ${TARFILE}
bzip2 ${TARFILE}
echo "Produced ${TARFILE}.bz2"
