#!/bin/bash
# Makes a tarball release
SPKVER=$(./version)
PREFIX=speakup-${SPKVER}
REL=${1:-v${SPKVER}}

TIMESTAMP=
if [ "$REL" != "v${SPKVER}" ]; then
	TIMESTAMP="_p`date +%Y%m%d`"
fi

TARFILE=${PREFIX}${TIMESTAMP}.tar.bz2

git archive --format=tar --prefix=${PREFIX}/ $REL | bzip2 > ${TARFILE}
echo "Produced ${TARFILE}"
