#!/bin/sh
echo "List of languages"
echo "1 Canadian English"
echo "2 Français UTF8"
echo "3 Français ISO-8859-1"
read -p "Choose the language " r
case $r in
  1)
    cp locales/en_CA/* /sys/accessibility/speakup/i18n
    speakupconf save
    ;;
  2)
    cp locales/fr/* /sys/accessibility/speakup/i18n
    speakupconf save
    ;;
  3)
    (
    	cd locales/fr
	for i in *
	do
	    iconv -f UTF-8 -t latin1 < $i > /sys/accessibility/speakup/i18n/$i
	done
    )
    speakupconf save
    ;;
  *)
esac
exit 0

