#!/bin/sh
# 
# talkwith -- switches speakup synthesizers on the fly
# and saves or loads speakup parameters
# 
# Copyright (c) 2009 by  the Speakup Team
# Copyright (c) 2008, 2009 by  Charles Hallenbeck
# 
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Requirements: Linux speakup 3.1.0 or later
#
# To install, copy this script to a directory on the execution path
# e.g. /usr/sbin, or /usr/local/sbin.
# This script should be run as root.

# Define some variables
SPEAKUPDIR="/sys/accessibility/speakup"
CONFDIR="/etc/speakup"
NOCONF="n" # do not save or load
#
if [ $(id -ru) -gt "0" ]
then
echo "`basename $0` must be run as root."
exit
fi
#
if [ ! -d $SPEAKUPDIR ]
then
echo "Speakup does not seem to be installed."
exit
fi
#
# Check the command line for options
if [ "$1" = "-n" ] || [ "$1" = "noconf" ]
then
NOCONF="y" # noconf
shift
fi
#
if [ "$1" = "" ]
then
echo
echo "Usage: `basename $0` [ noconf ] <synth> [ options ]"
echo
echo "If the synth name is espeak or spd, the option following "
echo "the name is simply passed along to espeakup or speechd-up."
echo
echo "Talkwith does not install or remove modules, so make sure any"
echo "required driver modules are installed before running talkwith."
echo "The correct driver for espeak and spd is speakup_soft."
echo
echo "If the noconf option is used, speakupconf will not be called"
echo " to load parameters."
echo
echo "You may select a synth name from the following list:"
echo "acntsa, acntpc, apollo, audptr, bns, dectlk, decext, decpc, dtlk,"
echo "espeak, keypc, ltlk, spd, spkout, txprt, dummy, or none."
echo
exit
fi
# 
# check for a valid synth name
#
if [ "$1" != "none" ] && \
# To disallow a particular device, comment out its line below:
[ "$1" != "acntsa" ] && \
[ "$1" != "acntpc" ] && \
[ "$1" != "apollo" ] && \
[ "$1" != "audptr" ] && \
[ "$1" != "bns" ] && \
[ "$1" != "dectlk" ] && \
[ "$1" != "decext" ] && \
[ "$1" != "decpc" ] && \
[ "$1" != "dtlk" ] && \
[ "$1" != "espeak" ] && \
[ "$1" != "keypc" ] && \
[ "$1" != "ltlk" ] && \
[ "$1" != "spkout" ] && \
[ "$1" != "spd" ] && \
[ "$1" != "txprt" ] && \
[ "$1" != "dummy" ] && \
# do not comment out the next line!
[ "$1" != "none" ]
then
echo "I didn't recognize the synthesizer type: \"$1\""
exit 
fi
# 
OLDMOD="`cat $SPEAKUPDIR/synth`"
NEWMOD=$1
if [ "$NEWMOD" = "espeak" ] || [ "$NEWMOD" = "spd" ]
then
if [ "$NEWMOD" = "espeak" ] && [ ! `which espeakup` ]
then
echo "espeakup does not seem to be available."
exit
fi
if [ "$NEWMOD" = "spd" ] && [ ! `which speechd-up` ]
then
echo "speechd-up does not seem to be available."
exit
fi
NEWMOD="soft"
fi
#
#
if [ "$OLDMOD" = "soft" ]
then
if pidof espeakup >/dev/null 2>&1
then
OLDVOX=espeak
else
OLDVOX=spd
fi
else
OLDVOX=$OLDMOD
fi
NEWVOX=$1
shift
#
echo "$NEWMOD" > $SPEAKUPDIR/synth
CURMOD=`cat $SPEAKUPDIR/synth` # Did the switch succeed?
if [ $CURMOD != $NEWMOD ]
then
	echo "Unable to change to $NEWMOD, aborting."
	exit 1
fi
if [ "$OLDMOD" = "soft" ]
then
kill -TERM `cat /var/run/speechd-up.pid 2>/dev/null` 2>/dev/null
kill -TERM `cat /var/run/espeakup.pid 2>/dev/null` 2>/dev/null
fi
sleep 2
if [ "$NEWVOX" = "none" ]
then
exit
fi
if [ "$NEWVOX" = "espeak" ]
then
espeakup $* >/dev/null 2>&1
else
if [ "$NEWVOX" = "spd" ]
then
nice -n 5 speechd-up $* 2>/dev/null
fi
fi


if [ ! -d $CONFDIR ]
then
	echo "$CONFDIR does not exist, so parameters cannot be loaded."
	NOCONF="n"
fi
#
if [ "$NOCONF" = "n" ]
then
# Load synth specific parameters
if [ $NEWVOX = "spd" ]
then
chmod u-r $CONFDIR/i18n/characters $CONFDIR/i18n/chartab
speakupconf load
chmod u+r $CONFDIR/i18n/characters $CONFDIR/i18n/chartab
else
speakupconf load
fi
fi

# end of talkwith
